/**
 * 从根 package.json 读取版本号，同步到：
 * - plugin/package.json
 * - ui/version.js（自动生成，供前端 import）
 */
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const rootPkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf-8'));
const version = rootPkg.version;

// 同步 plugin/package.json
const pluginPkgPath = resolve(root, 'plugin/package.json');
const pluginPkg = JSON.parse(readFileSync(pluginPkgPath, 'utf-8'));
if (pluginPkg.version !== version) {
  pluginPkg.version = version;
  writeFileSync(pluginPkgPath, JSON.stringify(pluginPkg, null, 2) + '\n');
  console.log(`  plugin/package.json → ${version}`);
} else {
  console.log(`  plugin/package.json already ${version}`);
}

// 生成 ui/version.js
const versionJs = `// Auto-generated by scripts/sync-version.mjs — do not edit\nexport const VERSION = '${version}';\n`;
const versionJsPath = resolve(root, 'ui/version.js');
writeFileSync(versionJsPath, versionJs);
console.log(`  ui/version.js → ${version}`);
